version: "3"
services:
  web:
    image: antonrudnev/teacherdb:poc
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8888:8888"
    networks:
      - webnet
networks:
  webnet: