version: "3"
services:
  web:
    image: antonrudnev/teacherdb:server
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "8888:8888"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet: